# This is a basic workflow to help you get started with Actions

name: Full-Site-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  # push:
  #   branches: [ preview ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ -d MWCDoc ] && rm -rf MWCDoc
          [ ! -d MWCDoc ] && mkdir -p MWCDoc
          [ ! -d mobile-web-capture-docs ] && git clone --depth 1 https://github.com/dynamsoft-docs/mobile-web-capture-docs.git mobile-web-capture-docs
          [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cd mobile-web-capture-docs && git pull && cd .. && cp -rfp ./mobile-web-capture-docs/* ./MWCDoc/
          cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./MWCDoc/
          cd MWCDoc && bundle exec jekyll build
          #python3 /home/ubuntu/ftp.py /home/ubuntu/MWCDoc/_site/ ./www.dynamsoft.com/mobile-web-capture/docs/ prod

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21
          local-dir: /home/ubuntu/MWCDoc/_site/
          server-dir: /www.dynamsoft.com/mobile-web-capture/docs/

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ -d MWCDocPreview ] && rm -rf MWCDocPreview
          [ -d mobile-web-capture-docs-preview ] && rm -rf mobile-web-capture-docs-preview
          [ ! -d MWCDocPreview ] && mkdir -p MWCDocPreview
          [ ! -d mobile-web-capture-docs-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/mobile-web-capture-docs.git mobile-web-capture-docs-preview
          cd mobile-web-capture-docs-preview && git pull && cd .. && cp -rfp ./mobile-web-capture-docs-preview/* ./MWCDocPreview/
          cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./MWCDocPreview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/MWCDocPreview/_config.yml
          cd MWCDocPreview && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500
          local-dir: /home/ubuntu/MWCDocPreview/_site/
          server-dir: /www.dynamsoft.com/mobile-web-capture/docs/
